uploads = []
generated = []

[[outputs]]
id = "l74q9qPdMXcvBD1LWH9H7"
uri = "file://dora-dungeons-source.tar.gz"
type = "unspecified"
title = "Dora Dungeons — Full Source Code"

[[outputs]]
id = "06xYpGadECAlQ09-DjcB3"
uri = "file://www-build.zip"
type = "unspecified"
title = "Dora Dungeons — Native-Ready www Build"

[[outputs]]
id = "oxVM8Pn6NCFQ_XAs-ffu3"
uri = "file://dora-dungeons-voltbuilder.zip"
type = "unspecified"
title = "Dora Dungeons — VoltBuilder Package"

[[outputs]]
id = "h814Bt7cKAV9pcqFbzCCT"
uri = "file://dora-dungeons-build.zip"
type = "unspecified"
title = "Dora Dungeons — Production Build (dist/public)"

[[outputs]]
id = "Bej0iuEE8ZYdrtARvgjdU"
uri = "file://www.zip"
type = "unspecified"
title = "www.zip — Dora Dungeons production build"
